server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/cambio_service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDIalect
  flyway:
    url: jdbc:postgresql://localhost:5432/
    schemas: cambio_service
    user: postgres
    password: postgres
    enabled: true
    validate-on-migrate: false
  sleuth:
    sampler:
      probability: 1.0
  #     porcentagem de rastreamento prod = 5%
springdoc:
  api-docs:
    path: cambio-service/v3/api-docs
