server:
  port: 8000
spring:
  application:
    name: cambio-service

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://172.19.0.2:5432/cambio_service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: create
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDIalect
  flyway:
    url: jdbc:postgresql://172.19.0.2:5432/
    schemas: cambio_service
    user: postgres
    password: postgres
    enabled: false

